### ISSUE TITLE
Leadins: overlapped icon images to the container

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/PZissis-and-Sons#12]
![image](https://cloud.githubusercontent.com/assets/17717843/15811480/af6bd3ea-2bdb-11e6-98a3-280d1fb49aa5.png)

**Comment by wajahat-titan** [comment]
Please try uploading png icons. if I try to fix this, the other icons will also get affected or we need to increase the size of circle. Please suggest
![screenshot](https://cloud.githubusercontent.com/assets/16283336/15919161/3ff12562-2e2c-11e6-9afe-6ed17f0adcdb.png)
