### ISSUE TITLE
Our Services: post content bullet is not styled

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/PZissis-and-Sons#18]
![image](https://cloud.githubusercontent.com/assets/17717843/15813851/ced14c88-2bf4-11e6-8f10-e008424353a9.png)

**Comment by wajahat-titan** [comment]
Content is not wrapped in ordered/un-ordered list. Please try uploading again.

![screenshot-1](https://cloud.githubusercontent.com/assets/16283336/15920171/79db1f68-2e35-11e6-80da-af5b7d65cd8c.jpg)

**Comment by dremensayson** [comment]
Step to Reproduce the issue:
From the Microsoft Word, copy the content then paste to the editor.
[Sample Content - With Label.docx](https://github.com/titan-cebu/PZissis-and-Sons/files/308165/Sample.Content.-.With.Label.docx)

**Comment by dremensayson** [comment]
Sorry, I forgot to mention the Privacy Policy Page also.
