### ISSUE TITLE
Our Clients: clipped company url

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/PZissis-and-Sons#19]
![image](https://cloud.githubusercontent.com/assets/17717843/15814376/ec7939c2-2bf8-11e6-8fd0-4160facc4b5f.png)

**Comment by wajahat-titan** [comment]
Only the url  label is clipped. if you click on this, complete url will be shown.
if I try to remove word limit it will broken on devices. please suggest
![screenshot](https://cloud.githubusercontent.com/assets/16283336/15919893/312d1e62-2e33-11e6-81fc-d549707adbff.png)

**Comment by dremensayson** [comment]
Hi,
It is ok if the url goes to 2nd line in the mobile devices which is better than the clipped one.
