### ISSUE TITLE
Contact Us: captcha is not implemented

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/PZissis-and-Sons#26]
![image](https://cloud.githubusercontent.com/assets/17717843/15815811/e780ea38-2c01-11e6-829e-7120389bcee0.png)

**Comment by wajahat-titan** [comment]
Required captcha is not available in gravity form plugin. Available captcha with plugin has been added.

**Comment by dremensayson** [comment]
implemented captcha is not match with the design
