### ISSUE TITLE
Contact Us: W3C 2 errors

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/PZissis-and-Sons#39]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fpzissis-and-sons-imp.stage.titanweb.com.au%2Fcontact-us%2F

![image](https://cloud.githubusercontent.com/assets/17717843/15956011/17348014-2f18-11e6-86d7-8df6b16801de.png)

**Comment by wajahat-titan** [comment]
These errors are from recaptcha(Gravity Form) and plugin files cannot be changed.

**Comment by dremensayson** [comment]
# 1 - plugin issue, so it won't fix, but #2 can be fix.

**Comment by wajahat-titan** [comment]
Both are of recaptcha. 
Please try removing recaptcha from gravity form and check. you will see no errors found.
